name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: |
          echo "slide=$(echo '${{ github.event.head_commit.message }}' | cut -d' ' -f 2)" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build -- slides/${{ env.slide }}.md --base /talks/${{ env.slide }}/

      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy.
          folder: dist
          # If you'd like to push the contents of the deployment folder into a
          # specific directory on the deployment branch you can specify it
          # here.
          target-folder: ${{ env.slide }}
          # You can use this option to delete files from your deployment
          # destination that no longer exist in your deployment source. One use
          # case is if your project generates hashed files that vary from build
          # to build. Using clean will not affect .git, .github, or .ssh
          # directories. This option is turned on by default and can be toggled
          # off by setting it to false.
          clean: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
